// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"filestoringservice/internal/application/service"
	"filestoringservice/internal/infrastructure/config"
	"filestoringservice/internal/infrastructure/hash"
	"filestoringservice/internal/infrastructure/persistence/postgres"
	"filestoringservice/internal/infrastructure/storage/s3"
	"filestoringservice/internal/interfaces/api/handler"
	"filestoringservice/internal/interfaces/api/router"
	hash2 "filestoringservice/internal/interfaces/hash"
	"filestoringservice/internal/interfaces/repository"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApplication wires up all the dependencies
func InitializeApplication() (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := postgres.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	fileRepository := postgres.NewFileRepository(db)
	fileStorage, err := s3.NewFileStorage(configConfig)
	if err != nil {
		return nil, err
	}
	blake3Hasher := hash.NewBLAKE3Hasher()
	fileService := service.NewFileService(fileRepository, fileStorage, blake3Hasher)
	fileHandler := handler.NewFileHandler(fileService)
	infoHandler := handler.NewInfoHandler()
	docsHandler := handler.NewDocsHandler()
	routerRouter := router.NewRouter(fileHandler, infoHandler, docsHandler)
	application := NewApplication(routerRouter, configConfig)
	return application, nil
}

// wire.go:

// RepositorySet provides repository implementations
var RepositorySet = wire.NewSet(postgres.NewFileRepository, wire.Bind(new(repository.FileRepository), new(*postgres.FileRepository)))

var HasherSet = wire.NewSet(hash.NewBLAKE3Hasher, wire.Bind(new(hash2.Hasher), new(*hash.BLAKE3Hasher)))

// Application is the main application container
type Application struct {
	Router *router.Router
	Config *config.Config
}

// NewApplication creates a new application
func NewApplication(router2 *router.Router, config2 *config.Config) *Application {
	return &Application{
		Router: router2,
		Config: config2,
	}
}
